#! /usr/bin/env bash

CMD=$1
VITE_DIR=${VITE_PROJECT_DIR:-frontend}
VITE_PRIMARY_PORT=${VITE_PRIMARY_PORT:-5173}
VITE_SECONDARY_PORT=${VITE_SECONDARY_PORT:-5273}
VITE_JS_PACKAGE_MGR=${VITE_JS_PACKAGE_MGR:-pnpm}

CMD=${CMD:=start}

if [ $CMD = start ]; then

  # Make sure the project directory is actually there
  if [ ! -d $VITE_DIR ]; then
    echo "ERROR: js project directory $VITE_DIR was expected, not found"
    exit 1
  fi

  if ! command -v $VITE_JS_PACKAGE_MGR >/dev/null; then
    echo "ERROR: could not find package manager $VITE_JS_PACKAGE_MGR"
    exit 1
  fi

  # make sure node_modules has linux and not mac code:
  cd $VITE_DIR
  $VITE_JS_PACKAGE_MGR install

  # Is js project a Vite project?
  if [ ! -d node_modules/vite ]; then
    echo "ERROR: project in $VITE_DIR does not appear to be Vite-enabled"
    exit 1
  fi

  # create a background tmux session and tell it to run
  # our vite script
  tmux kill-session -t vite-sess 2>/dev/null
  tmux new -s vite-sess -d
  tmux send "node node_modules/vite/bin/vite.js --port $VITE_PRIMARY_PORT --host" C-m
  echo "Vite now serving $VITE_DIR"

# stopping
elif [ $CMD = stop ]; then
  echo "stopping vite"
  # kill the vite session
  tmux kill-session -t vite-sess

# show settings
elif [ $CMD = status ]; then
  echo "ViteServe Status"
  echo "================"
  echo "Project: $VITE_PROJECT_DIR"
  echo "Vite Primary Port: $VITE_PRIMARY_PORT"
  echo "Vite Secondary Port: $VITE_SECONDARY_PORT"

# usage
else
  echo "$0 start|stop|status"
fi
